apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: ebpf-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      initContainers:
      - name: attach
        imagePullPolicy: Always
        image: khj010909/ebpf:3.0.1
        env:
          - name: POD_UID
            valueFrom: { fieldRef: { fieldPath: metadata.uid}}
        securityContext:
          privileged: true
          runAsUser: 0
          # capabilities:
          #   add: ["NET_ADMIN","BPF","SYS_ADMIN"]
        volumeMounts:
          - name:  bpf
            mountPath: /sys/fs/bpf
            readOnly: false
      volumes:
        - name:  bpf
          hostPath:
            path: /sys/fs/bpf
            type: Directory
      containers:
      - name: reader
        image: khj010909/ebpf-reader:3.0.1
        env:
          - name: POD_UID
            valueFrom: { fieldRef: { fieldPath: metadata.uid}}
        volumeMounts:
          - name:  bpf
            mountPath: /sys/fs/bpf
            readOnly: false
        securityContext:
          runAsUser: 0
          # capabilities:
          #   add: ["NET_ADMIN","BPF","SYS_ADMIN"]
      - name: server
        image: alpine:3.20
        command: ["/bin/sh", "-c", "sleep infinity"]
        ports:
        - containerPort: 5678